name: Build LaTeX document, upload it as a release and ping the website repo
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{github.run_id}}
          release_name: Release ${{github.run_id}}
      - name: Upload PDF to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
    
      - name: Ping repo once release is created
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_PUBLIC_TOKEN }}
          repository: rahul-sundaresan/gatsby-resume
          event-type: update_resume
  
